// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"technical_test_skyshi/activity/controller"
	"technical_test_skyshi/activity/repository/mysql"
	"technical_test_skyshi/activity/service"
	"technical_test_skyshi/database"
	"technical_test_skyshi/router"
	controller2 "technical_test_skyshi/todo/controller"
	mysql2 "technical_test_skyshi/todo/repository/mysql"
	service2 "technical_test_skyshi/todo/service"
)

// Injectors from injector.go:

func InitServer() *gin.Engine {
	activityRepository := mysql.NewMysqlAcitivity()
	db := database.InitDBMysql()
	activityService := service.NewActivityServiceImpl(activityRepository, db)
	activityController := controller.NewActivityControllerImpl(activityService)
	todoRepository := mysql2.NewMysqlTodo()
	todoService := service2.NewTodoServiceImpl(todoRepository, db)
	todoController := controller2.NewTodoControllerImpl(todoService)
	engine := router.SetupRouter(activityController, todoController)
	return engine
}
